#!/usr/bin/env bash
set -e

BASE=$(cd $(dirname "$0") && pwd -P)

# Remove empty directories under mock-home because otherwise these are
# part of the test and can create problems for earlier, buggy versions
# of the symlinker, blowing up regression tests that check out old
# versions.
#
find $BASE/t/mock-home -type d -empty -delete

cd "$BASE"
[ -e bats/bin/bats ] || {
    echo >&2 'Did not find bats executable. `git submodule update --init`?'
    exit 1
}
bats/bin/bats "${@:-t/}"
