#!/usr/bin/env bash
set -e

basedir=$(cd $(dirname "$0") && pwd -P)

warn() { echo >&2 "$(basename $0):" "$@"; }

check_submodules() {
    count=$(git submodule status --recursive | sed -n -e '/^[^ ]/p' | wc -l)
    [ $count -eq 0 ] || {
        warn "$count Git submodules are not up to date"
        warn 'Run `git submodule update --init`?'
    }
}

############################################################
# Main

# We use `sort` and various other localized commands in the tests;
# make sure that we always have a consistent sorting order regardless
# of the user's locale.
#
export LC_COLLATE=C

cd "$basedir"
check_submodules
bats/bin/bats "${@:-t/}"
