#!/usr/bin/env bash
set -e

basedir=$(cd $(dirname "$0") && pwd -P)

warn() { echo >&2 "$(basename $0):" "$@"; }

check_submodules() {
    count=$(git submodule status --recursive | sed -n -e '/^[^ ]/p' | wc -l)
    [ $count -eq 0 ] || {
        warn "$count Git submodules are not up to date"
        warn 'Run `git submodule update --init`?'
    }
}

############################################################
# Main

# We use `sort` and various other localized commands in the tests;
# make sure that we always have a consistent sorting order regardless
# of the user's locale.
#
export LC_COLLATE=C

# Remove empty directories under mock-home because otherwise these are
# part of the test and can create problems for earlier, buggy versions
# of the symlinker, blowing up regression tests that check out old
# versions.
#
find $basedir/t/mock-home -type d -empty -delete

cd "$basedir"
check_submodules
bats/bin/bats "${@:-t/}"
